<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../config/db.php';
$pageTitle='Customers';$priceLists=$conn->query("SELECT id,name FROM price_lists WHERE status='Active' ORDER BY name")->fetchAll();
$q=trim((string)($_GET['q']??'')); $status=(string)($_GET['status']??'');
$sql="SELECT c.*, pl.name AS price_list_name, (SELECT COUNT(*) FROM sales s WHERE s.customer_id=c.id AND s.sale_status='Completed') sales_count FROM customers c LEFT JOIN price_lists pl ON pl.id=c.price_list_id WHERE 1=1"; $p=[];
if($q!==''){ $sql.=" AND (c.customer_name LIKE :q OR c.phone LIKE :q OR c.email LIKE :q)"; $p[':q']="%{$q}%"; }
if(in_array($status,['Active','Inactive'],true)){ $sql.=" AND c.status=:status"; $p[':status']=$status; }
$sql.=" ORDER BY c.id DESC"; $st=$conn->prepare($sql); $st->execute($p); $customers=$st->fetchAll();
$stats=['active'=>(int)$conn->query("SELECT COUNT(*) FROM customers WHERE status='Active'")->fetchColumn(),'credit'=>(float)$conn->query("SELECT COALESCE(SUM(balance),0) FROM customers")->fetchColumn(),'sales'=>(int)$conn->query("SELECT COUNT(*) FROM sales WHERE sale_status='Completed'")->fetchColumn()];
$flash=$_SESSION['customer_flash']??null; unset($_SESSION['customer_flash']);
require_once __DIR__.'/../../includes/header.php'; require_once __DIR__.'/../../includes/sidebar.php'; ?>
<main class="content"><style>
.page-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:22px;flex-wrap:wrap}.page-head h1{margin:0}.muted{color:#64748b}.btn{display:inline-flex;align-items:center;gap:7px;padding:10px 15px;border-radius:8px;text-decoration:none;border:0;cursor:pointer;font-weight:700;font-size:13px}.btn-primary{background:#004a99;color:#fff}.btn-light{background:#eef2f7;color:#334155}.btn-success{background:#047857;color:#fff}.btn-danger{background:#fee2e2;color:#b91c1c}
.stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-bottom:20px}.stat,.card{background:#fff;border-radius:12px;padding:18px;box-shadow:0 1px 4px #00000012}.stat strong{display:block;font-size:24px}.stat span{color:#64748b;font-size:13px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;background:#fff;padding:15px;border-radius:12px;margin-bottom:15px;box-shadow:0 1px 4px #00000012}.toolbar input,.toolbar select,.form-grid input,.form-grid textarea,.form-grid select{padding:10px 12px;border:1px solid #dbe3ec;border-radius:8px}.toolbar input{min-width:300px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:1000px}.table th{background:#004a99;color:#fff;text-align:left;padding:12px;font-size:12px}.table td{padding:12px;border-bottom:1px solid #e5e7eb;font-size:13px}.badge{padding:5px 9px;border-radius:20px;font-size:11px;font-weight:700}.active{background:#dcfce7;color:#166534}.inactive{background:#fee2e2;color:#991b1b}.flash{padding:12px 15px;border-radius:9px;margin-bottom:18px;background:#ecfdf5;color:#166534;border:1px solid #bbf7d0}.modal{display:none;position:fixed;inset:0;background:#0008;z-index:2000;align-items:center;justify-content:center;padding:20px}.modal.show{display:flex}.modal-box{background:#fff;border-radius:15px;padding:24px;width:min(700px,100%);max-height:92vh;overflow:auto;position:relative}.close{position:absolute;right:18px;top:12px;border:0;background:none;font-size:28px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-grid label{font-size:12px;font-weight:700;color:#475569}.form-grid input,.form-grid select,.form-grid textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px}.form-grid textarea{min-height:90px;resize:vertical}.full{grid-column:1/-1}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}@media(max-width:700px){.stats-grid,.form-grid{grid-template-columns:1fr}}
</style>
<div class="page-head"><div><h1>Customers</h1><p class="muted">Manage customer accounts, credit limits and outstanding balances.</p></div><button class="btn btn-primary" onclick="document.getElementById('customerModal').classList.add('show')"><i class="fas fa-plus"></i> Add Customer</button></div>
<?php if($flash):?><div class="flash"><?=e($flash)?></div><?php endif;?>
<div class="stats-grid"><div class="stat"><strong><?=number_format($stats['active'])?></strong><span>Active Customers</span></div><div class="stat"><strong>KES <?=number_format($stats['credit'],2)?></strong><span>Outstanding Credit</span></div><div class="stat"><strong><?=number_format($stats['sales'])?></strong><span>Completed Sales</span></div></div>
<form class="toolbar" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search customer, phone or email..."><select name="status"><option value="">All statuses</option><option value="Active" <?=$status==='Active'?'selected':''?>>Active</option><option value="Inactive" <?=$status==='Inactive'?'selected':''?>>Inactive</option></select><button class="btn btn-light"><i class="fas fa-search"></i> Filter</button><a class="btn btn-light" href="<?=BASE_URL?>/modules/customers/index.php">Reset</a></form>
<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>Credit Limit</th><th>Price List</th><th>Balance</th><th>Sales</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php if(!$customers):?><tr><td colspan="9" style="text-align:center;padding:45px;color:#64748b">No customers found.</td></tr><?php else:foreach($customers as $c):?>
<tr><td><strong><?=e($c['customer_name'])?></strong><br><small class="muted"><?=e($c['address']??'')?></small></td><td><?=e($c['phone']?:'—')?></td><td><?=e($c['email']?:'—')?></td><td>KES <?=number_format((float)$c['credit_limit'],2)?></td><td><?=e($c['price_list_name']?:'Normal Price')?></td><td><strong>KES <?=number_format((float)$c['balance'],2)?></strong></td><td><?=number_format((int)$c['sales_count'])?></td><td><span class="badge <?=strtolower($c['status'])?>"><?=e($c['status'])?></span></td><td><a class="btn btn-light" href="edit.php?id=<?=(int)$c['id']?>">Edit</a></td></tr>
<?php endforeach;endif;?></tbody></table></div></div></main>
<div id="customerModal" class="modal"><div class="modal-box"><button class="close" type="button" onclick="document.getElementById('customerModal').classList.remove('show')">&times;</button><h2>Add Customer</h2><p class="muted">Create a customer account for cash or credit sales.</p><form method="post" action="store.php"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-grid">
<label>Customer Name *<input name="customer_name" required maxlength="150"></label><label>Phone *<input name="phone" required maxlength="30"></label><label>Email<input type="email" name="email" maxlength="150"></label><label>Price List<select name="price_list_id"><option value="">Normal Price (Default)</option><?php foreach($priceLists as $pl):?><option value="<?=$pl['id']?>"><?=e($pl['name'])?></option><?php endforeach;?></select></label><label>Credit Limit<input type="number" name="credit_limit" min="0" step="0.01" value="0"></label><label class="full">Address<textarea name="address"></textarea></label><label class="full">Notes<textarea name="notes"></textarea></label></div><div class="actions"><button type="button" class="btn btn-light" onclick="document.getElementById('customerModal').classList.remove('show')">Cancel</button><button class="btn btn-success">Save Customer</button></div></form></div></div>
<?php require_once __DIR__.'/../../includes/footer.php'; ?>