<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/auth.php'; require_once __DIR__.'/../../config/db.php';
$pageTitle='Sales / POS';
$products=$conn->query("SELECT p.id,p.product_name,p.sku,p.barcode,p.selling_price,p.wholesale_price,p.stock_quantity,p.unit,b.brand_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id WHERE p.status='Active' ORDER BY p.product_name")->fetchAll();
$customers=$conn->query("SELECT id,customer_name,phone,credit_limit,balance FROM customers WHERE status='Active' ORDER BY customer_name")->fetchAll();
$stats=[
'today'=>(float)$conn->query("SELECT COALESCE(SUM(total_amount),0) FROM sales WHERE sale_status='Completed' AND DATE(sale_date)=CURDATE()")->fetchColumn(),
'month'=>(float)$conn->query("SELECT COALESCE(SUM(total_amount),0) FROM sales WHERE sale_status='Completed' AND YEAR(sale_date)=YEAR(CURDATE()) AND MONTH(sale_date)=MONTH(CURDATE())")->fetchColumn(),
'credit'=>(float)$conn->query("SELECT COALESCE(SUM(balance),0) FROM customers")->fetchColumn()
];
$recent=$conn->query("SELECT s.id,s.invoice_number,s.sale_date,s.total_amount,s.paid_amount,s.balance,s.payment_method,COALESCE(c.customer_name,'Walk-in Customer') customer_name FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.sale_status='Completed' ORDER BY s.id DESC LIMIT 12")->fetchAll();
$flash=$_SESSION['sale_flash']??null;unset($_SESSION['sale_flash']);
require_once __DIR__.'/../../includes/header.php';require_once __DIR__.'/../../includes/sidebar.php';?>
<main class="content"><style>
.pos-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;gap:15px;flex-wrap:wrap}.pos-head h1{margin:0}.muted{color:#64748b}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.stat,.panel{background:#fff;border-radius:12px;padding:18px;box-shadow:0 1px 4px #00000012}.stat strong{display:block;font-size:23px}.stat span{font-size:12px;color:#64748b}.pos{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(340px,.9fr);gap:18px}.search{display:flex;gap:10px;margin-bottom:12px}.search input,.field input,.field select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #dbe3ec;border-radius:8px}.product-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-height:590px;overflow:auto}.product{border:1px solid #e2e8f0;border-radius:10px;padding:13px;background:#fff;cursor:pointer}.product:hover{border-color:#004a99;box-shadow:0 2px 8px #00000010}.product strong{display:block}.product small{color:#64748b}.price{font-weight:800;color:#004a99;margin-top:8px}.out{opacity:.5;cursor:not-allowed}.cart{min-height:300px}.cart-row{display:grid;grid-template-columns:1fr 65px 80px 25px;gap:7px;align-items:center;border-bottom:1px solid #edf2f7;padding:10px 0;font-size:12px}.cart-row input{width:55px;padding:6px;border:1px solid #dbe3ec;border-radius:6px}.remove{border:0;background:none;color:#dc2626;cursor:pointer}.totals{margin-top:12px;border-top:1px solid #e2e8f0;padding-top:12px}.total-line{display:flex;justify-content:space-between;margin:7px 0}.grand{font-size:20px;font-weight:800}.field{margin:11px 0}.field label{display:block;font-size:12px;font-weight:700;color:#475569;margin-bottom:5px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:8px;padding:11px 15px;font-weight:700;cursor:pointer}.primary{background:#004a99;color:#fff}.success{background:#047857;color:#fff;width:100%;margin-top:10px}.light{background:#eef2f7;color:#334155}.danger{background:#fee2e2;color:#991b1b}.table-wrap{overflow:auto;margin-top:18px}.table{width:100%;border-collapse:collapse;min-width:900px}.table th{background:#004a99;color:#fff;text-align:left;padding:11px;font-size:12px}.table td{padding:11px;border-bottom:1px solid #e5e7eb;font-size:13px}.flash{padding:12px;background:#ecfdf5;color:#166534;border-radius:8px;margin-bottom:15px}.empty{text-align:center;color:#94a3b8;padding:45px}@media(max-width:1000px){.pos{grid-template-columns:1fr}.product-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.stats{grid-template-columns:1fr}.product-grid{grid-template-columns:1fr}}
</style>
<div class="pos-head"><div><h1>Sales / POS</h1><p class="muted">Create sales, collect payments and update inventory in one transaction.</p></div><a class="btn light" href="<?=BASE_URL?>/modules/customers/index.php"><i class="fas fa-users"></i> Customers</a></div>
<?php if($flash):?><div class="flash"><?=e($flash)?></div><?php endif;?>
<div class="stats"><div class="stat"><strong>KES <?=number_format($stats['today'],2)?></strong><span>Today's Sales</span></div><div class="stat"><strong>KES <?=number_format($stats['month'],2)?></strong><span>This Month</span></div><div class="stat"><strong>KES <?=number_format($stats['credit'],2)?></strong><span>Outstanding Customer Credit</span></div></div>
<form method="post" action="store.php" id="saleForm" class="pos"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="panel"><div class="search"><input id="productSearch" placeholder="Search product, SKU or barcode..."><button type="button" class="btn light" onclick="document.getElementById('productSearch').value='';filterProducts()">Clear</button></div><div id="productGrid" class="product-grid">
<?php foreach($products as $p):?><div class="product <?=$p['stock_quantity']<=0?'out':''?>" data-search="<?=e(strtolower($p['product_name'].' '.$p['sku'].' '.$p['barcode'].' '.$p['brand_name']))?>" onclick="<?=$p['stock_quantity']>0?'addProduct('.(int)$p['id'].')':'void(0)'?>"><strong><?=e($p['product_name'])?></strong><small><?=e($p['brand_name']?:'Generic')?> · <?=e($p['sku']?:'No SKU')?></small><div class="price">KES <?=number_format((float)$p['selling_price'],2)?> · Stock <?=number_format((float)$p['stock_quantity'],2)?></div></div><?php endforeach;?></div></div>
<div class="panel"><h3 style="margin-top:0">Current Sale</h3><div class="field"><label>Customer</label><select name="customer_id" id="customer_id"><option value="">Walk-in Customer</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>" data-limit="<?=$c['credit_limit']?>" data-balance="<?=$c['balance']?>"><?=e($c['customer_name'])?> — <?=e($c['phone'])?></option><?php endforeach;?></select></div><div id="cart" class="cart"><div class="empty">Click products to add them to the sale.</div></div><input type="hidden" name="cart_json" id="cart_json"><div class="field"><label>Discount (KES)</label><input type="number" name="discount" id="discount" min="0" step=".01" value="0"></div><div class="field"><label>Tax (KES)</label><input type="number" name="tax" id="tax" min="0" step=".01" value="0"></div><div class="field"><label>Payment Method</label><select name="payment_method" id="payment_method"><option>Cash</option><option>M-Pesa</option><option>Bank</option><option>Credit</option><option>Mixed</option></select></div><div class="field"><label>Amount Paid (KES)</label><input type="number" name="paid_amount" id="paid_amount" min="0" step=".01" value="0"></div><div class="field"><label>Notes</label><input name="notes" maxlength="500"></div><div class="totals"><div class="total-line"><span>Subtotal</span><strong id="subtotal">KES 0.00</strong></div><div class="total-line"><span>Discount</span><strong id="discountView">KES 0.00</strong></div><div class="total-line"><span>Tax</span><strong id="taxView">KES 0.00</strong></div><div class="total-line grand"><span>Total</span><strong id="total">KES 0.00</strong></div><div class="total-line"><span>Balance</span><strong id="balance">KES 0.00</strong></div></div><button class="btn success" type="submit"><i class="fas fa-check"></i> Complete Sale</button></div></form>
<div class="panel table-wrap"><h3>Recent Sales</h3><table class="table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Total</th><th>Paid</th><th>Balance</th><th>Method</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><strong><?=e($r['invoice_number'])?></strong></td><td><?=e($r['sale_date'])?></td><td><?=e($r['customer_name'])?></td><td>KES <?=number_format((float)$r['total_amount'],2)?></td><td>KES <?=number_format((float)$r['paid_amount'],2)?></td><td>KES <?=number_format((float)$r['balance'],2)?></td><td><?=e($r['payment_method'])?></td></tr><?php endforeach;?></tbody></table></div>
</main>
<script>
const products=<?=json_encode(array_map(fn($p)=>['id'=>(int)$p['id'],'name'=>$p['product_name'],'sku'=>$p['sku'],'price'=>(float)$p['selling_price'],'wholesale'=>(float)$p['wholesale_price'],'stock'=>(float)$p['stock_quantity'],'unit'=>$p['unit']],$products),JSON_UNESCAPED_UNICODE)?>;
let cart=[];
function addProduct(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return;const row=cart.find(x=>x.id===id);if(row){if(row.qty<p.stock)row.qty++;}else cart.push({...p,qty:1});render();}
function render(){const box=document.getElementById('cart');if(!cart.length){box.innerHTML='<div class="empty">Click products to add them to the sale.</div>';}else{box.innerHTML=cart.map((x,i)=>'<div class="cart-row"><div><strong>'+esc(x.name)+'</strong><br><small>KES '+money(x.price)+'</small></div><input type="number" min="1" max="'+x.stock+'" value="'+x.qty+'" onchange="setQty('+i+',this.value)"><span>KES '+money(x.price*x.qty)+'</span><button type="button" class="remove" onclick="removeItem('+i+')">&times;</button></div>').join('');}calc();}
function setQty(i,v){let q=Math.max(1,Math.min(Number(v)||1,cart[i].stock));cart[i].qty=q;render();}
function removeItem(i){cart.splice(i,1);render();}
function calc(){let sub=cart.reduce((a,x)=>a+x.qty*x.price,0),d=Math.max(0,Number(document.getElementById('discount').value)||0),t=Math.max(0,Number(document.getElementById('tax').value)||0),total=Math.max(0,sub-d+t),paid=Math.max(0,Number(document.getElementById('paid_amount').value)||0);document.getElementById('subtotal').textContent='KES '+money(sub);document.getElementById('discountView').textContent='KES '+money(d);document.getElementById('taxView').textContent='KES '+money(t);document.getElementById('total').textContent='KES '+money(total);document.getElementById('balance').textContent='KES '+money(Math.max(0,total-paid));document.getElementById('cart_json').value=JSON.stringify(cart.map(x=>({id:x.id,qty:x.qty,price:x.price})));}
function filterProducts(){const q=document.getElementById('productSearch').value.toLowerCase();document.querySelectorAll('.product').forEach(x=>x.style.display=x.dataset.search.includes(q)?'block':'none');}
function money(n){return Number(n).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
document.getElementById('productSearch').addEventListener('input',filterProducts);document.getElementById('discount').addEventListener('input',calc);document.getElementById('tax').addEventListener('input',calc);document.getElementById('paid_amount').addEventListener('input',calc);document.getElementById('payment_method').addEventListener('change',()=>{if(document.getElementById('payment_method').value==='Credit')document.getElementById('paid_amount').value=0;calc();});
document.getElementById('saleForm').addEventListener('submit',e=>{if(!cart.length){e.preventDefault();alert('Add at least one product to the sale.');return;}const total=cart.reduce((a,x)=>a+x.qty*x.price,0)-Number(document.getElementById('discount').value||0)+Number(document.getElementById('tax').value||0);const paid=Number(document.getElementById('paid_amount').value||0);const method=document.getElementById('payment_method').value;if(paid>total){e.preventDefault();alert('Amount paid cannot exceed the sale total.');return;}if(method==='Credit' && !document.getElementById('customer_id').value){e.preventDefault();alert('Select a customer for credit sales.');return;}});
render();
</script><?php require_once __DIR__.'/../../includes/footer.php'; ?>